import NextTopLoader from "nextjs-toploader";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader
          color="#5E35CC"
          height={3}
          speed={500}
          showSpinner={false}
        />
        {children}
      </body>
    </html>
  );
}
